server:
  port: 8888
  undertow:
    worker-threads: 2000
    io-threads: 5000

app:
  name : uploader
  defaultContainer: temp



filesClient:
  username: testuser:swift
  password: tthksqNaJdS6RvNaOh9p5aTRu5qkMDCLITi7iYFM
  account:
  authenticationURL: http://192.168.6.93/auth/
  connectionTimeOut: 60000


spring:
  jackson:
    default-property-inclusion: non_null

  datasource:
    username: root
    password: 123123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:32769/xuchun?useUnicode=true&characterEncoding=UTF-8